In [23]:
import numpy as np

def analyse_dataset(n):
    x = np.load('Datasets/kryptonite-%s-X.npy'%(n))
    y = np.load('Datasets/kryptonite-%s-y.npy'%(n))

    means = x.mean(axis=0)
    std = x.mean(axis=0)

    mean0 = x[y==0].mean(axis=0)
    mean1 = x[y==1].mean(axis=0)
    diff = mean0 - mean1
    
    correlation_matrix = np.corrcoef(x, rowvar=False)
    
    return means,std, diff, correlation_matrix



In [28]:
means, std, diff, corr_m = analyse_dataset(10)

print(np.round(corr_m,3))


[[ 1.     0.004 -0.     0.005 -0.     0.006  0.004  0.005  0.003 -0.004]
 [ 0.004  1.    -0.001  0.004 -0.007 -0.01   0.006  0.006 -0.016  0.001]
 [-0.    -0.001  1.     0.011 -0.001  0.001  0.007 -0.002 -0.004  0.004]
 [ 0.005  0.004  0.011  1.     0.001 -0.016 -0.009  0.004  0.001 -0.002]
 [-0.    -0.007 -0.001  0.001  1.    -0.003  0.007 -0.    -0.006  0.004]
 [ 0.006 -0.01   0.001 -0.016 -0.003  1.    -0.001 -0.004  0.015  0.013]
 [ 0.004  0.006  0.007 -0.009  0.007 -0.001  1.    -0.003 -0.009  0.012]
 [ 0.005  0.006 -0.002  0.004 -0.    -0.004 -0.003  1.     0.001  0.007]
 [ 0.003 -0.016 -0.004  0.001 -0.006  0.015 -0.009  0.001  1.    -0.002]
 [-0.004  0.001  0.004 -0.002  0.004  0.013  0.012  0.007 -0.002  1.   ]]


In [29]:
print(diff)

[ 0.02128983  0.01786793  0.00938706 -0.00106062 -0.00386471 -0.01568905
 -0.00151362 -0.00018734  0.00736233  0.00715283]


Why the dataset is difficult to fit:
- diff: the class-conditional mean difference is consistently near zero. This indicates that the average feature values for samples labelled 0 and 1 are nearly identical
- the correlation matrices are all arounds 0 apart from the diagonal, suggesting no correlation between features